version: '3.1'

services:
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - mynetwork
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
      ME_CONFIG_BASICAUTH_USERNAME: ''
      ME_CONFIG_BASICAUTH_PASSWORD: ''
    depends_on:
      - mongo

  nestjs-auth:
    image: marcomelilli/mynestjsapp
    build: .
    command: npm run start
    restart: always
    ports:
      - 3000:3000
    volumes:
      - nestjsdata:/usr/src/app
    networks:
      - mynetwork
    depends_on:
      - mongo

volumes:
  mongodata:
  nestjsdata:

networks:
  mynetwork:
